server:
  port: 8021
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:5432/${POSTGRES_DB:data_analyzer_microservice}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:1505Duma}
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
topics: ${KAFKA_SUBSCRIBED_TOPICS:data-temperature,data-power,data-voltage}


